//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaUchet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchetUSPEntities : DbContext
    {
        public UchetUSPEntities()
            : base("name=UchetUSPEntities")
        {
        }
        public static UchetUSPEntities _context;
        public static UchetUSPEntities GetContext()
        {
            if (_context == null)
                _context = new UchetUSPEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Группы> Группы { get; set; }
        public virtual DbSet<Дисциплины> Дисциплины { get; set; }
        public virtual DbSet<Кафедры> Кафедры { get; set; }
        public virtual DbSet<Преподаватели> Преподаватели { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
    }
}
