//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кафедры
    {
        public int КодКафедры { get; set; }
        public string НазваниеКафедры { get; set; }
        public string Факультет { get; set; }
        public string ФИОЗаведующего { get; set; }
        public int НомерКорпуса { get; set; }
        public string Телефон { get; set; }
        public int КоличествоПреподавателей { get; set; }
    }
}
