//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public int КодСтудента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int КодКафедры { get; set; }
        public int КодГруппы { get; set; }
        public System.DateTime ГодРождения { get; set; }
        public string Пол { get; set; }
        public string Адрес { get; set; }
        public string Город { get; set; }
        public string Телефон { get; set; }
    }
}
